function printDecoration(codename)

switch upper(codename)
    case 'MELANIE' % MELANIE = seMiautomatic dEep LeArniNg pIplinE
        disp([  newline, ' __  __ ______ _      ',...
                '         _   _ _____ ______ ',newline,...
                                '|  \/  |  ____| |     ',...
                '   /\   | \ | |_   _|  ____|',newline,...
                                '| \  / | |__  | |     ',...
                '  /  \  |  \| | | | | |__   ',newline,...
                                '| |\/| |  __| | |     ',...
                ' / /\ \ | . ` | | | |  __|  ',newline,...
                                '| |  | | |____| |____ ',...
                '/ ____ \| |\  |_| |_| |____ ',newline,...
                                '|_|  |_|______|______/',...
                '_/    \_\_| \_|_____|______|',newline]);
                       disp([newline,'        seMiautomatic',...
                ' dEep LeArniNg pIplinE ',newline]);
    case 'FELIPE'  
        disp([  newline, ' ______ ______ _      ',...
                '_____ _____  ______ ',newline,...
                                '|  ____|  ____| |    |',...
                '_   _|  __ \|  ____|',newline,...
                                '| |__  | |__  | |     ',...
                ' | | | |__) | |__   ',newline,...
                                '|  __| |  __| | |     ',...
                ' | | |  ___/|  __|  ',newline,...
                                '| |    | |____| |____ ',...
                '_| |_| |    | |____ ',newline,...
                                '|_|    |______|______|',...
                '_____|_|    |______|',newline]); 
                        disp([newline,'       Fully automat',...
                'ic dEep LearnIng PipelinE ',newline]);
     otherwise
        disp(':-)');
end

disp(['           JN Kather 2015-2019, @jnkath',newline,newline]);
        

end